import React, { useState } from 'react';
import tellie from 'assets/images/token-gated/tellie.svg';
import link from 'assets/images/token-gated/link.svg';

import Modal from 'components/Commons/Modal';
import Image from 'next/image';

export default function UploadByLinkHelperModal({ show, handleClose }) {
  return (
    <Modal
      width={600}
      height={800}
      overflow='scroll'
      show={show}
      handleClose={() => handleClose()}
      showCloseIcon={true}
    >
      <div className='p-4 !leading-relaxed !break-words'>
        <p className='text-txtblack font-black text-[24px]'>
          How to get the link
        </p>
        <div className='mt-4'>
          <p className='text-[20px] font-semibold text-txtblack'>
            Step 1: Upload your files
          </p>
          <p className='mt-4 text-textSubtle '>
            Before you begin, you will need somewhere to host your file(s). If
            you don't already have one, you can try either{' '}
            <a
              href='https://www.dropbox.com/'
              className='mr-1 text-primary-900'
              target='_blank'
              rel='noreferrer'
            >
              Dropbox
            </a>
            (up to 2 GB storage free) or{' '}
            <a
              href='https://google.com/drive/'
              className='mr-1 text-primary-900'
              target='_blank'
              rel='noreferrer'
            >
              Google Drive
            </a>
            (up to 15 GB storage free). For blockchain hosting, where the
            benefit is permanent and decentralized storage, you can try{' '}
            <a
              href='https://permafy.com/'
              className='mr-1 text-primary-900'
              target='_blank'
              rel='noreferrer'
            >
              Permify
            </a>
            which allows you to upload files of any size (50¢ for files up to
            500MB + 1¢ for every MB after).
          </p>
        </div>
        <div className='mt-4'>
          <p className='text-[20px] font-semibold text-txtblack'>
            Step 2: Prepare your links
          </p>
          <p className='mt-4 text-textSubtle'>
            The share link generated by most services will take people to a page
            to download the file. In order to prevent that from happening, you
            will have to make some small changes to the default share URLs
            generated by your file host. By making these changes, you will make
            it so that when someone clicks on your Decir link, the file will
            direct download, rather than opening a new page. 🙌
          </p>
          <p className='text-[18px] font-semibold text-txtblack mt-4'>
            Instructions for Dropbox:
          </p>
          <ul className='list-disc	text-textSubtle ml-4 mt-4'>
            <li>
              Hover over the file you'd like to share, and select the share
              icon.
            </li>
            <li>
              Make sure that the file is set to "Anyone with this link can view.
            </li>
            <li>Click "Copy Link".</li>
            <li>Your link will end with "dl=0" -- Change the 0 to a 1.</li>
          </ul>
          <p className='text-[18px] font-semibold text-txtblack mt-4'>
            Instructions for Google Drive:
          </p>
          <ul className='list-disc	text-textSubtle ml-4  mt-4'>
            <li>
              From your drive, right-click on the file you'd like to share via
              download link.
            </li>
            <li>
              Select "Share" and under "General Access" make sure that "Anyone
              with the link" can "View".
            </li>
            <li>Click "Copy Link".</li>
            <li>
              Go to this site and enter the link you copied:
              <a
                href='https://sites.google.com/site/gdocs2direct/'
                className='mr-1 text-primary-900'
                target='_blank'
                rel='noreferrer'
              >
                https://sites.google.com/site/gdocs2direct/
              </a>{' '}
            </li>
          </ul>
        </div>{' '}
        <div className='mt-4'>
          <p className='text-[20px] font-semibold text-txtblack'>
            Step 3: Add your link
          </p>
          <Image
            src={tellie}
            height={246}
            width={483}
            className='rounded object-cover mt-4'
            alt='decir dashboard'
          ></Image>
          <p className='mt-4 text-textSubtle'>
            From any Token gated Dashboard Page, open the Page Designer by
            tapping the “upload by link” Button on the upper left.
          </p>
        </div>{' '}
        <div className='mt-4'>
          <p className='text-[20px] font-semibold text-txtblack'>
            Step 4: Select your content type
          </p>
          <Image
            src={link}
            height={246}
            width={483}
            className='rounded object-cover mt-4'
            alt='decir dashboard'
          ></Image>
          <p className='mt-4 text-textSubtle'>
            Paste the link on the field and select type of the files that you
            want to upload. and your file is ready to upload.
          </p>
        </div>{' '}
      </div>
    </Modal>
  );
}
